inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Naming/MethodName:
  Exclude:
    - test/adapters/integration.rb
    - test/adapters/rack_test.rb

