inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/DoubleNegation:
  Enabled: false

