inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - examples/**/*.rb

Layout/LineLength:
  Exclude:
    - spec/**/*.rb
    - examples/**/*.rb

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
