# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{faraday}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rick"]
  s.date = %q{2010-01-05}
  s.description = %q{HTTP/REST API client library with pluggable components}
  s.email = %q{technoweenie@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "faraday.gemspec",
     "lib/faraday.rb",
     "lib/faraday/adapter/mock_request.rb",
     "lib/faraday/adapter/net_http.rb",
     "lib/faraday/adapter/typhoeus.rb",
     "lib/faraday/connection.rb",
     "lib/faraday/error.rb",
     "lib/faraday/loadable.rb",
     "lib/faraday/request/post_request.rb",
     "lib/faraday/request/yajl_request.rb",
     "lib/faraday/response.rb",
     "lib/faraday/response/yajl_response.rb",
     "lib/faraday/test_connection.rb",
     "test/adapter/typhoeus_test.rb",
     "test/adapter_test.rb",
     "test/connection_test.rb",
     "test/helper.rb",
     "test/live_server.rb",
     "test/response_test.rb"
  ]
  s.homepage = %q{http://github.com/technoweenie/faraday}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{HTTP/REST API client library}
  s.test_files = [
    "test/adapter/typhoeus_test.rb",
     "test/adapter_test.rb",
     "test/connection_test.rb",
     "test/helper.rb",
     "test/live_server.rb",
     "test/response_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

