#!/usr/bin/env ruby
# Usage: script/release
# Build the package, tag a commit, push it to origin, and then release the
# package publicly.

require File.expand_path("../ruby", __FILE__)

system "script/package"
system "git commit --allow-empty -a -m 'Release #{MakeScript.version}'"
system "git tag v#{MakeScript.version}"
system "git push origin"
system "git push origin v#{MakeScript.version}"
system "gem push pkg/#{MakeScript.gem_file}"

