#!/usr/bin/env ruby
# Usage: script/release
# Build the gem, tag a commit, push to origin, and push the gem to Rubyforge.

require File.expand_path("../ruby", __FILE__)

system "script/gem"
system "git commit --allow-empty -a -m 'Release #{MakeScript.version}'"
system "git tag v#{MakeScript.version}"
system "git push origin"
system "git push origin v#{MakeScript.version}"
system "gem push pkg/#{MakeScript.gem_file}"

