# SITE CONFIGURATION
url: 'https://lostisland.github.io'
baseurl: '/faraday'
repository: 'lostisland/faraday'

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  title: Faraday
  avatar: assets/img/logo.png
  favicon: assets/img/favicon.png
  # email: your-email@example.com
  description: >-
    Simple, but flexible HTTP client library, with support for multiple backends
  footer_text: "&copy; 2009 - 2020, the <a class=\"body-link\" href=\"/faraday/team\">Faraday Team</a>. Website and branding design by <a href=\"https://elelopic.design\" target=\"_blank\">Elena Lo Piccolo</a>."

  # Icons
  github: 'lostisland/faraday'
  gitter: 'lostisland/faraday'

  # Post navigation
  post_navigation: true
  site_navigation_sort: 'order'

# BUILD SETTINGS
markdown: kramdown
remote_theme: rohanchandra/type-theme

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# GitHub settings
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
